### ISSUE TITLE
Convenience API: pseudoCancellable

### ISSUE THREAD

**Issue by adam-rocska** [srmagura/real-cancellable-promise#6]
# Feature Value

At the time of writing the aforementioned function's contract is distributed as follows:
```ts
export declare function pseudoCancellable<T>(promise: PromiseLike<T>): CancellablePromise<T>;
```

For the world's most simplistic use cases (like writing tests) yields the following simplest usage:
```ts
   const {result, rerender, waitForNextUpdate} = renderHook(() =>
    useTaskQueue({
      name: 'test',
      codec: json.number,
      task: v => pseudoCancellable(Promise.resolve([v * 2])),
    })
  );
```

It would be nice to extend the API by providing an overload which supports the following usage:
```ts
   const {result, rerender, waitForNextUpdate} = renderHook(() =>
    useTaskQueue({
      name: 'test',
      codec: json.number,
      task: v => pseudoCancellable([v * 2]),
    })
  );
```
* or similar

**Comment by srmagura** [comment]
Hi @adam-rocska, you can also write

```tsx
CancellablePromise.resolve([v * 2])
``` 

which should have nearly the same behavior as `pseudoCancellable(Promise.resolve([v * 2]))`. Does that address your concern?

**Comment by adam-rocska** [comment]
Sure, it should do the trick. This is just a convenience idea ¯\_(ツ)_/¯ 

If it doesn't fit the lib', I'm cool with it.

**Comment by srmagura** [comment]
Yeah, I'm hesitant to introduce new APIs when it can already be accomplished with an existing function. You can always define your own function if this is a common pattern in your codebase 😃
